# Config file for automatic testing at travis-ci.org

language: python

python:
  - "3.3"
  - "2.7"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
    - pip install -U . --use-mirrors
    - pip install coveralls --use-mirrors

# command to run tests, e.g. python setup.py test
script: 
    nosetests --with-coverage --cover-package=rcfile

after_success:
    coveralls
